apiVersion: v1
kind: Service
metadata:
  name: nexus
  namespace: buildit-jenkins
spec:
  ports:
  - name: ui
    protocol: TCP
    port: 80
    targetPort: 8081
  selector:
    app: nexus
  clusterIP: None
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: nexus-pv-claim
  namespace: buildit-jenkins
spec:
  storageClassName: fast
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nexus
  namespace: buildit-jenkins
spec:
  selector:
    matchLabels:
      app: nexus
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: nexus
    spec:
      securityContext:
        fsGroup: 2000
      containers:
      - image: sonatype/nexus3:3.9.0
        name: nexus
        ports:
        - containerPort: 8081
          name: http
        volumeMounts:
        - name: nexus-persistent-storage
          mountPath: /nexus-data
      volumes:
      - name: nexus-persistent-storage
        persistentVolumeClaim:
          claimName: nexus-pv-claim